# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  raylib_wave_shooter_config = debug_x64
  raylib_config = debug_x64

else ifeq ($(config),debug_x86)
  raylib_wave_shooter_config = debug_x86
  raylib_config = debug_x86

else ifeq ($(config),debug_arm64)
  raylib_wave_shooter_config = debug_arm64
  raylib_config = debug_arm64

else ifeq ($(config),release_x64)
  raylib_wave_shooter_config = release_x64
  raylib_config = release_x64

else ifeq ($(config),release_x86)
  raylib_wave_shooter_config = release_x86
  raylib_config = release_x86

else ifeq ($(config),release_arm64)
  raylib_wave_shooter_config = release_arm64
  raylib_config = release_arm64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := raylib-wave-shooter raylib

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

raylib-wave-shooter: raylib
ifneq (,$(raylib_wave_shooter_config))
	@echo "==== Building raylib-wave-shooter ($(raylib_wave_shooter_config)) ===="
	@${MAKE} --no-print-directory -C . -f raylib-wave-shooter.make config=$(raylib_wave_shooter_config)
endif

raylib:
ifneq (,$(raylib_config))
	@echo "==== Building raylib ($(raylib_config)) ===="
	@${MAKE} --no-print-directory -C . -f raylib.make config=$(raylib_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f raylib-wave-shooter.make clean
	@${MAKE} --no-print-directory -C . -f raylib.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  debug_x86"
	@echo "  debug_arm64"
	@echo "  release_x64"
	@echo "  release_x86"
	@echo "  release_arm64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   raylib-wave-shooter"
	@echo "   raylib"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"
